#define IS_UPPER_CASE(c) ( ( (c) >= 'A') && ( (c) <= 'Z') )
#define IS_LOWER_CASE(c) ( ( (c) >= 'a') && ( (c) <= 'z') )
#define IS_ALPHABETIC(c) ( ( IS_LOWER_CASE(c)) || (IS_UPPER_CASE(c) ) )
#define IS_DIGIT(c)      ( ( (c) >= '0' ) && ( (c) <= '9' ) )
#define IS_SPECIAL(c)    ( !( IS_DIGIT(c) ) && !( IS_ALPHABETIC(c) ) )
